[programs.localnet]
solana_gif_portal_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ramonparis/.config/solana/id.json"

[scripts]
test = "ts-node tests/solana-gif-portal-program.ts"
