[programs.devnet]
solana_gif_portal_program = "9SF35gQGQH1r3vcAvTo8BhYs99fYXwDmKRJDArezcVYQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ramonparis/.config/solana/id.json"

[scripts]
test = "ts-node tests/solana-gif-portal-program.ts"
